POST http://localhost:3000/users/register
Content-Type: application/json

{
    "fullName": "Habeeb",
    "email": "lukman.oladokun2@gmail.com",
    "password": "lukman3"
}

###
GET http://localhost:3000/users/auth/verify-email/38c2f9c7-c2d6-41b1-80fb-8d90384665a2

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "lukman.oladokun2@gmail.com",
    "password": "lukman3"
}

###


PUT     http://localhost:3000/users/user/668eb7cd8e86e265f0b0a540
Content-Type: application/json

{
    "email": "kane@kane.com",
    "password": "elu123"
}


###

GET http://localhost:3000/users/user/ec919d25-4284-4168-a76f-d905bae51423

### 

GET http://localhost:3000/users

###

DELETE http://localhost:3000/users/user/66887f933cba576c35c1684b

