POST http://localhost:3000/users/register
Content-Type: application/json

{
    "fullName": "Luku Pay",
    "email": "lukupay@gmail.com",
    "password": "lukupay"
}

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "kane@kane.co",
    "password": "elu123"
}

###


PUT     http://localhost:3000/users/user/668eb7cd8e86e265f0b0a540
Content-Type: application/json

{
    "email": "kane@kane.com",
    "password": "elu123"
}


###

GET http://localhost:3000/users/user/668eb7cd8e86e265f0b0a540

### 

GET http://localhost:3000/users

###

DELETE http://localhost:3000/users/user/66887f933cba576c35c1684b

