POST http://localhost:3000/users/register
Content-Type: application/json

{
    "fullName": "Eluku kane",
    "email": "peter@code.com",
    "password": "pet123"
}

###

PUT     http://localhost:3000/users/user/668eb7cd8e86e265f0b0a540
Content-Type: application/json

{
    "email": "kane@kane.com",
    "password": "elu123"
}


###

GET http://localhost:3000/users/user/668eb7cd8e86e265f0b0a540

### 

GET http://localhost:3000/users

###

DELETE http://localhost:3000/users/user/66887f933cba576c35c1684b

